### ISSUE TITLE
Crash omni.kit.window.toolbar when enabling this extension

### ISSUE THREAD

**Issue by MarqRazz** [mati-nvidia/custom-kinds-example#1]
Hello,

First off I wanted to say thank you for taking the time to make this example extension!

I have it working and can view the custom Kinds created...
![image](https://github.com/mati-nvidia/custom-kinds-example/assets/25058794/4a36d1c2-4bac-4373-bf7a-cdf2510ff736)

but when I load the new extension it causes `omni.kit.window.toolbar-1.5.4` and `omni.physx.zerogravity-105.1.12-5.1` to crash when starting Isaac Sim. If I look in the extension manager at the Toolbar extension it says `Failed to solve extension dependency` 
![image](https://github.com/mati-nvidia/custom-kinds-example/assets/25058794/678cb0aa-e724-489d-b46c-ab837d4d5620)

Here is the console output of the error when Isaac is loading.
```
2024-01-22 13:58:51 [5,777ms] [Error] [omni.ext._impl._internal] Failed to import python module omni.kit.window.toolbar from /home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.window.toolbar. Error: expected str, bytes or os.PathLike object, not NoneType. Traceback:
Traceback (most recent call last):
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/omni/ext/_impl/_internal.py", line 187, in _custom_importer
    return _import_public(ext_module.path, ext_module.name, reload_enabled)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/carb/profiler/__init__.py", line 83, in wrapper
    r = f(*args, **kwds)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/omni/ext/_impl/_internal.py", line 94, in _import_public
    module = import_module(module_name)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/carb/profiler/__init__.py", line 83, in wrapper
    r = f(*args, **kwds)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/omni/ext/_impl/custom_importer.py", line 76, in import_module
    return importlib.import_module(name)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.window.toolbar/omni/kit/window/toolbar/__init__.py", line 1, in <module>
    from .toolbar import *
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.window.toolbar/omni/kit/window/toolbar/toolbar.py", line 20, in <module>
    from omni.kit.widget.toolbar.builtin_tools.builtin_tools import BuiltinTools  # backward compatible
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.widget.toolbar/omni/kit/widget/toolbar/builtin_tools/builtin_tools.py", line 13, in <module>
    from .select_button_group import SelectButtonGroup
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.widget.toolbar/omni/kit/widget/toolbar/builtin_tools/select_button_group.py", line 28, in <module>
    EXTENSION_FOLDER_PATH = pathlib.Path(
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

2024-01-22 13:58:51 [5,777ms] [Error] [carb.scripting-python.plugin] Exception: Extension python module: 'omni.kit.window.toolbar' in '/home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/exts/omni.kit.window.toolbar' failed to load.

At:
  /home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/omni/ext/_impl/_internal.py(213): startup
  /home/mimic/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/kernel/py/omni/ext/_impl/_internal.py(328): startup_extension
  PythonExtension.cpp::startup()(2): <module>

2024-01-22 13:58:51 [5,777ms] [Error] [omni.ext.plugin] [ext: omni.kit.window.toolbar-1.5.4] Failed to startup python extension.
```

Any suggestions on how I can get the custom Kind extension to play nice with the Toolbar?

Thanks!

**Comment by mati-nvidia** [comment]
Hi @MarqRazz. Looks like there's a typo in `omni.kit.widget.toolbar` that is only executed when you add custom kinds. I've filed an internal ticket for it, but if you want to work around it for now here's the code you need to change. Replace `key` with `k`.

![image](https://github.com/mati-nvidia/custom-kinds-example/assets/105014919/8b9d2809-550e-4837-ac91-e77bc174e002)

**Comment by MarqRazz** [comment]
Thanks so much for your help @mati-nvidia! I'm closing this since you opened an upstream issue.

**Comment by mati-nvidia** [comment]
No problem. The internal issue number is `OM-119072` in case you want to keep an eye out for a fix in future release notes.
